
import apoorva.Apoorva;
import java.awt.PopupMenu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sheetal
 */
public class LoginFinal extends javax.swing.JFrame {

    String bill_item1 = new String();
    String bill_amt1 = new String();
    DefaultListModel starter = new DefaultListModel();
    DefaultListModel desserts = new DefaultListModel();
    DefaultListModel drinks = new DefaultListModel();
    DefaultListModel snacks = new DefaultListModel();
    DefaultListModel orders = new DefaultListModel();
    DefaultListModel bill_b = new DefaultListModel();
    int j = 1, k = 0, ll = 1;
    float total = 0;
    String s = new String();

    /**
     * Creates new form LoginFinal
     *
     */
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement preparedStatement;

    public LoginFinal() {
        initComponents();
        conn = Apoorva.connectDB();
        System.out.println("UI");
    }

    void processLogin() {
        try {
            System.out.println("Button Ciced");
            String sql = "SELECT * FROM login WHERE name = ? AND password = ?";
            preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, jtxtName.getText());
            preparedStatement.setString(2, jtxtPassword.getText());
            rs = preparedStatement.executeQuery();
            if (rs.next()) {
                
        
        
                JOptionPane.showMessageDialog(null, "Login Successful!!!", "Login", JOptionPane.INFORMATION_MESSAGE);
                jPanelParent.removeAll();
                jPanelParent.add(jPanelMenu);
                jPanelParent.revalidate();
                jPanelParent.repaint();
                //    String argsPass[] = new String[2];
                //    Hotel_Management.main(argsPass);

            } else {
                JOptionPane.showMessageDialog(null, "Login Unsuccessful!!!", "Login", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (SQLException e) {
            System.out.println("Error " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jspnQuantity = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        quan_submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanelParent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbtnSubmit = new javax.swing.JButton();
        jtxtName = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jPanelCust = new javax.swing.JPanel();
        jButtonCust = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtCustN = new javax.swing.JTextField();
        jTxtCustP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTxtCustPt = new javax.swing.JTextField();
        jPanelMenu = new javax.swing.JPanel();
        jbtnStarters = new javax.swing.JButton();
        jbtnDesserts = new javax.swing.JButton();
        jbtnDrinks = new javax.swing.JButton();
        jbtnSnacks = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanelOptions = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMenuList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jMenuChoice = new javax.swing.JList<>();
        jBtnBackk = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListBill = new javax.swing.JList<>();
        jBtnBack = new javax.swing.JButton();

        jLabel3.setText("Quantity");

        quan_submit.setText("go");
        quan_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quan_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jspnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(quan_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jspnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(quan_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        jLabel4.setText("jLabel4");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanelParent.setLayout(new java.awt.CardLayout());

        jLabel1.setText("USERNAME");

        jLabel2.setText("PASSWORD");

        jbtnSubmit.setText("LOGIN");
        jbtnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSubmitActionPerformed(evt);
            }
        });

        jtxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNameActionPerformed(evt);
            }
        });

        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addGap(194, 194, 194)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jbtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jbtnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanel1, "card5");

        jButtonCust.setText("GO TO BILL");
        jButtonCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustActionPerformed(evt);
            }
        });

        jLabel7.setText("Name of customer");

        jLabel8.setText("Contact no");

        jTxtCustN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCustNActionPerformed(evt);
            }
        });

        jLabel5.setText("Points");

        jTxtCustPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCustPtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCustLayout = new javax.swing.GroupLayout(jPanelCust);
        jPanelCust.setLayout(jPanelCustLayout);
        jPanelCustLayout.setHorizontalGroup(
            jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustLayout.createSequentialGroup()
                .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCustLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButtonCust, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCustLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addGroup(jPanelCustLayout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(16, 16, 16)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148)
                        .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCustPt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCustP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtCustN, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanelCustLayout.setVerticalGroup(
            jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCustLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCustN, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCustP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanelCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCustPt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(jButtonCust, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelCust, "card4");

        jbtnStarters.setText("STARTERS");
        jbtnStarters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnStartersActionPerformed(evt);
            }
        });

        jbtnDesserts.setText("DESERTS");
        jbtnDesserts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDessertsActionPerformed(evt);
            }
        });

        jbtnDrinks.setText("DRINKS");
        jbtnDrinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDrinksActionPerformed(evt);
            }
        });

        jbtnSnacks.setText("SNACKS");
        jbtnSnacks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSnacksActionPerformed(evt);
            }
        });

        jbtnExit.setText(" STORE CUSTOMER DETAILS");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jButton1.setText("CHECK CUSTOMERS DATABASE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnStarters, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(jbtnDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnDesserts, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jbtnSnacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(234, 234, 234))
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnStarters, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jbtnDesserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSnacks, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelMenu, "card6");

        jMenuList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jMenuList);

        jScrollPane2.setViewportView(jMenuChoice);

        jBtnBackk.setText("BACK");
        jBtnBackk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOptionsLayout = new javax.swing.GroupLayout(jPanelOptions);
        jPanelOptions.setLayout(jPanelOptionsLayout);
        jPanelOptionsLayout.setHorizontalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOptionsLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelOptionsLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jBtnBackk, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        jPanelOptionsLayout.setVerticalGroup(
            jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOptionsLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(10, 10, 10)
                .addComponent(jBtnBackk, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanelOptions, "card5");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jButton2.setText("BACK TO MENU");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        jPanelParent.add(jPanel3, "card6");

        getContentPane().add(jPanelParent, "card4");

        jListBill.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jListBill);

        jBtnBack.setText("BACK");
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(410, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jBtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnBack)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSubmitActionPerformed
        processLogin();


    }//GEN-LAST:event_jbtnSubmitActionPerformed
    void setStarter() {

    }
    private void jbtnStartersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnStartersActionPerformed
        jMenuList.setModel(starter);
        starter.removeAllElements();
        starter.addElement("TIKKI  -200");
        starter.addElement("KABAB  -100");
        starter.addElement("CRISP  -600");
        starter.addElement("TANDOOR-700");
        jPanelParent.removeAll();
        jPanelParent.add(jPanelOptions);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jbtnStartersActionPerformed

    private void jbtnDessertsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDessertsActionPerformed
        jMenuList.setModel(desserts);
        desserts.removeAllElements();
        desserts.addElement("BROWNIE-800");
        desserts.addElement("CHOCOOS-900");
        desserts.addElement("MALLOWS-700");
        desserts.addElement("WALNUTS-500");
        jPanelParent.removeAll();
        jPanelParent.add(jPanelOptions);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jbtnDessertsActionPerformed

    private void quan_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quan_submitActionPerformed
        // TODO add your handling code here:
        jDialog1.show(false);
        String choice = jMenuList.getSelectedValue();
        // System.out.println(choice);
        int i = 0, note;
        while (true) {
            char ch = choice.charAt(i);
            if (ch == '-') {
                note = i;
                break;
            }
            i++;
        }
        //System.out.println(note);
        String bill_item = choice.substring(0, note);
        String bill_amt = choice.substring(note + 1);
        int flag = 0, a2 = 0, c = 0;
        int amt = Integer.valueOf(bill_amt);
        StringBuilder str = new StringBuilder();
        int value = (Integer) jspnQuantity.getValue();
        System.out.println(value);
//System.out.println(bill_item1);
        loop1:
        for (int a1 = 0; a1 < 20; a1++) {
            try {
                char h = bill_item.charAt(a1);

            } catch (java.lang.StringIndexOutOfBoundsException e3) {

                System.out.println(a1);
                str.ensureCapacity(19 - a1);
                while (c < (19 - a1)) {
                    str.insert(c, ' ');
                    c++;
                }
                System.out.println(str.length());
                break loop1;
            }
        }
        total = total + amt * value;
        String ss = str.toString();
        bill_item = bill_item.concat(ss);
        System.out.println(bill_item);
        String bill_bill = bill_item.concat(String.valueOf(amt * value));
        System.out.println(bill_bill.length());
        jMenuChoice.setModel(bill_b);
        if (ll == 1) {
            String ip = "ITEM                PRICE";
            bill_b.add(0, ip);
            ll = 0;
        }
        while (true) {

            bill_b.add(j, bill_bill);
            j++;
            break;
        }

        jPanelParent.removeAll();
        jPanelParent.add(jPanelOptions);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_quan_submitActionPerformed

    private void jbtnDrinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDrinksActionPerformed
        // TODO add your handling code here:
        jMenuList.setModel(drinks);
        drinks.removeAllElements();
        drinks.addElement("FANTAA-200");
        drinks.addElement("FROOTI-100");
        drinks.addElement("SPRITE-600");
        drinks.addElement("MN.DEW-700");
        jPanelParent.removeAll();
        jPanelParent.add(jPanelOptions);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jbtnDrinksActionPerformed

    private void jbtnSnacksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSnacksActionPerformed
        // TODO add your handling code here:

        jMenuList.setModel(snacks);
        snacks.removeAllElements();
        snacks.addElement("NOODLE-200");
        snacks.addElement("SAMOSA-100");
        snacks.addElement("PASTAS-600");
        snacks.addElement("PIZZAS-700");
        jPanelParent.removeAll();
        jPanelParent.add(jPanelOptions);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jbtnSnacksActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        // TODO add your handling code here:
        jPanelParent.removeAll();
        jPanelParent.add(jPanelCust);
        jPanelParent.revalidate();
        jPanelParent.repaint();


    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        // TODO add your handling code here:
        jPanelParent.removeAll();
        jPanelParent.add(jPanel2);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jBtnBackActionPerformed


    private void jtxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNameActionPerformed

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPasswordActionPerformed

    private void jTxtCustPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCustPtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCustPtActionPerformed

    private void jTxtCustNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCustNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCustNActionPerformed

    private void jButtonCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustActionPerformed
        // when i click proceed to menu
        Connection conn2 = null;
        Connection con4 = null;
        Connection conn4 = null;
       
        int f = 0;
        ResultSet rs3 = null;
        String o = "0";
        PreparedStatement preparedStatement2;
        conn2 = Apoorva.connectDB();
        con4 = Apoorva.connectDB();
        conn4 = Apoorva.connectDB();
        
        try {
            String add = "INSERT INTO CUST (name, phone, points) VALUES (?,?,?)";
            preparedStatement2 = conn2.prepareStatement(add);
            o = jTxtCustP.getText();
            preparedStatement2.setString(1, jTxtCustN.getText());
            preparedStatement2.setString(2, o);
            preparedStatement2.setString(3, jTxtCustPt.getText());
            preparedStatement2.executeUpdate();
            System.out.println("Inserted");
        } catch (SQLException e4) {
            System.out.println("Error catched" + e4);
        }
        jPanelParent.removeAll();
        jPanelParent.add(jMenuChoice);
        jPanelParent.revalidate();
        jPanelParent.repaint();
        String t = "TOTAL ";
        bill_b.add(j++, t.concat(String.valueOf(total)));
        bill_b.add(j++, t.concat("AFTER GST ".concat(String.valueOf(total + total * 0.12))));

        try {
            String d = "SELECT * FROM CUST";
          //  String add2 = "INSERT INTO CUST ( points) VALUES (?)";
           
            PreparedStatement p;
            p = conn2.prepareStatement(d);
            rs3 = p.executeQuery();
            
            while (rs3.next()) {
                String ss = rs3.getString("name");
                String pn = rs3.getString("phone");
                int pt = rs3.getInt("points");
                System.out.println(ss+ " " +pt);
                if ((pn).equals(o) && pt!=0) {
                    //System.out.println("hi");
                    bill_b.add(j, t.concat("AFTER previous billings if any ".concat(String.valueOf(total + total * 0.12 - total * 0.01 * pt))));
                     f = (int) total / 100;
                    System.out.println(f+" yo "+pt);
                   
                        System.out.println("test 1");
                        String yo = "DELETE FROM CUST WHERE phone = ? AND points = ?";
                PreparedStatement psp;
                  psp = conn.prepareStatement(yo);
                  
                  psp.setString(1,pn);
                  psp.setInt(2,pt);
                  psp.execute();
            String add3 = "UPDATE CUST SET points = ? WHERE phone =  ?";
           PreparedStatement p5;
            p5 = con4.prepareStatement(add3);
                 int poinT; 
                  p5.setInt(1,pt+f );
                    p5.setString(2,pn);
                  poinT = p5.executeUpdate();
                  System.out.println("updated");
                   
                   
                    System.out.println("deleted");
            break;
                }
               if ((pn).equals(o) && pt==0)
                {
                     String add3 = "UPDATE CUST"+" SET points = ?"+" WHERE phone =  ?";
            //String add2 = "INSERT INTO CUST ( points) VALUES (?)";
             System.out.println("updated");
           
            PreparedStatement p5;
            p5 = con4.prepareStatement(add3);
         //   p5 = conn4.prepareStatement(add3);
                   int poinT; 
                    f = (int) total / 100;
                    /*int j = pt+f;*/
                    p5.setInt(1,pt+f );
                    p5.setString(2,pn);
                  poinT = p5.executeUpdate();
                   break;
                }
            }
        } catch (SQLException e6) {
            System.out.println(e6);
        }

    }//GEN-LAST:event_jButtonCustActionPerformed

    private void jBtnBackkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackkActionPerformed
        // TODO add your handling code here:
        jPanelParent.removeAll();
        jPanelParent.add(jPanelMenu);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jBtnBackkActionPerformed

    private void jMenuListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuListMousePressed
        // TODO add your handling code here:
        System.out.println("Method called");
        String slct = jMenuList.getSelectedValue();
        jDialog1.show(true);
        jDialog1.setSize(300, 500);

        System.out.println(slct);

    }//GEN-LAST:event_jMenuListMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection cnc = null;
        ResultSet rsr = null;
        cnc = Apoorva.connectDB();
        PreparedStatement psps = null;
        String ring = "SELECT * FROM CUST";
        try{
        psps = cnc.prepareStatement(ring);
        rsr = psps.executeQuery(ring);
        jTable1.setModel(DbUtils.resultSetToTableModel(rsr));
        
        }
        catch(Exception eee)
        {
            
        }
        jPanelParent.removeAll();
        jPanelParent.add(jPanel3);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPanelParent.removeAll();
        jPanelParent.add(jPanelMenu);
        jPanelParent.revalidate();
        jPanelParent.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        new LoginFinal().setVisible(true);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        int total = 0;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jBtnBackk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCust;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListBill;
    private javax.swing.JList<String> jMenuChoice;
    private javax.swing.JList<String> jMenuList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCust;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelOptions;
    private javax.swing.JPanel jPanelParent;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTxtCustN;
    private javax.swing.JTextField jTxtCustP;
    private javax.swing.JTextField jTxtCustPt;
    private javax.swing.JButton jbtnDesserts;
    private javax.swing.JButton jbtnDrinks;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnSnacks;
    private javax.swing.JButton jbtnStarters;
    private javax.swing.JButton jbtnSubmit;
    private javax.swing.JSpinner jspnQuantity;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JButton quan_submit;
    // End of variables declaration//GEN-END:variables

    private void send(JTextField jTxtCustN) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
